spring:
  config:
    activate:
      on-profile: local

# Dev local: cho phép ddl-auto update nếu không chạy Flyway
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.deprecation: off

tikzy:
  seed:
    admin:
      enabled: true
      password: ${TIKZY_SEED_ADMIN_PASSWORD:Admin@123456}
